# Generated by Django 6.1.1 on 2026-09-19 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_security', models.CharField(choices=[('TLS', 'TLS/STARTTLS'), ('SSL', 'SSL/TLS')], default='TLS', max_length=20)),
                ('smtp_username', models.CharField(max_length=255)),
                ('smtp_app_password_encrypted', models.TextField()),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('imap_security', models.CharField(choices=[('TLS', 'TLS/STARTTLS'), ('SSL', 'SSL/TLS')], default='SSL', max_length=20)),
                ('imap_username', models.CharField(max_length=255)),
                ('imap_app_password_encrypted', models.TextField()),
                ('default_signature', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_imap_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=50, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
