# Generated by Django 6.1.1 on 2026-09-19 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermailaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Sales General Inbox', max_length=255, unique=True)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_security', models.CharField(choices=[('TLS', 'TLS/STARTTLS'), ('SSL', 'SSL/TLS')], default='TLS', max_length=20)),
                ('smtp_username', models.CharField(max_length=255)),
                ('smtp_app_password_encrypted', models.TextField()),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('imap_security', models.CharField(choices=[('TLS', 'TLS/STARTTLS'), ('SSL', 'SSL/TLS')], default='SSL', max_length=20)),
                ('imap_username', models.CharField(max_length=255)),
                ('imap_app_password_encrypted', models.TextField()),
                ('default_signature', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_imap_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=50, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usermailaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mail_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='accounts.mailaccount'),
        ),
    ]
