# Generated by Django 6.1.1 on 2026-09-19 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mailaccount_remove_usermailaccount_user_and_more'),
        ('prospects', '0011_alter_outreachemail_sender_mail_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMailAccount',
        ),
    ]
