# Generated by Django 6.1.1 on 2026-09-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_usermailaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='imap_status',
            field=models.CharField(choices=[('CONFIGURED', 'Configured'), ('CONNECTED', 'Connected'), ('FAILED', 'Failed')], default='CONFIGURED', max_length=20),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='smtp_status',
            field=models.CharField(choices=[('CONFIGURED', 'Configured'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='CONFIGURED', max_length=20),
        ),
    ]
