# Generated by Django 6.1.1 on 2026-09-19 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mailaccount_imap_status_mailaccount_smtp_status'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
    ]
