# Generated by Django 6.1.1 on 2026-09-19 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mailaccount_company_userprofile_company'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
    ]
