# Generated by Django 6.1.1 on 2026-09-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_mailaccount_company_alter_userprofile_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailaccount',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
    ]
