# Generated by Django 6.1.1 on 2026-10-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_timezone'),
        ('whatsapp', '0008_rename_whatsapp_co_session_deleted_idx_whatsapp_wh_session_8fe92a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_sessions',
            field=models.ManyToManyField(blank=True, related_name='assigned_profiles', to='whatsapp.whatsappsession'),
        ),
    ]
