# Generated by Django 6.1.1 on 2026-09-26 05:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospects', '0024_callbackreminder_prospect_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(default='default', help_text='WAHA session name (matches WAHA session ID).', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('STARTING', 'Starting'), ('QR_REQUIRED', 'QR Required'), ('AUTHENTICATED', 'Authenticated'), ('READY', 'Ready'), ('DISCONNECTED', 'Disconnected'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], default='DISCONNECTED', max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_status', models.CharField(blank=True, max_length=50, null=True)),
                ('send_count', models.BigIntegerField(default=0)),
                ('receive_count', models.BigIntegerField(default=0)),
                ('failed_send_count', models.BigIntegerField(default=0)),
                ('consecutive_failed_sends', models.IntegerField(default=0)),
                ('disconnect_count', models.IntegerField(default=0)),
                ('reconnect_count', models.IntegerField(default=0)),
                ('outbound_block_count', models.BigIntegerField(default=0)),
                ('cooldown_block_count', models.BigIntegerField(default=0)),
                ('opt_out_count', models.BigIntegerField(default=0)),
                ('last_successful_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_failed_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_failed_message_error', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Session',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_enabled', models.BooleanField(default=False, help_text='Master kill switch for outbound WhatsApp messages. Set to False to immediately stop all outbound sends.')),
                ('safety_stop_active', models.BooleanField(default=False, help_text='Activated by the Safety Guard on abnormal send failures. Requires manual Super Admin review and reset to resume.')),
                ('safety_stop_reason', models.TextField(blank=True, null=True)),
                ('safety_stop_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_cooldown_minutes', models.IntegerField(default=120, help_text='Minimum minutes between messages to the same recipient.')),
                ('global_hourly_limit', models.IntegerField(default=50, help_text='Maximum total outbound messages allowed per hour.')),
                ('per_user_hourly_limit', models.IntegerField(default=20, help_text='Maximum outbound messages per user per hour.')),
                ('consecutive_failure_threshold', models.IntegerField(default=5, help_text='Number of consecutive send failures before the Safety Guard triggers an automatic outbound stop.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('safety_stop_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_safety_stops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(help_text='WhatsApp chat ID in format: <digits>@c.us', max_length=100, unique=True)),
                ('is_matched', models.BooleanField(default=False, help_text='True only when linked to an authorized ProspectContact.')),
                ('unread_count', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, max_length=200, null=True)),
                ('last_message_from_me', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='prospects.prospect')),
                ('prospect_contact', models.ForeignKey(blank=True, help_text='The Key Person associated with this WhatsApp contact.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='prospects.prospectcontact')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='whatsapp.whatsappsession')),
            ],
            options={
                'verbose_name': 'WhatsApp Conversation',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, help_text='SHA256 idempotency key. Prevents duplicate sends.', max_length=64, unique=True)),
                ('waha_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound (sent)'), ('INBOUND', 'Inbound (received)')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked (Safety Guard)')], default='PENDING', max_length=20)),
                ('body_preview', models.CharField(blank=True, help_text='First 500 chars of message body (for admin reference only).', max_length=500, null=True)),
                ('body_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('message_type', models.CharField(default='chat', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('waha_timestamp', models.DateTimeField(blank=True, help_text='Timestamp from the WAHA event/response.', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappconversation')),
                ('performed_by', models.ForeignKey(blank=True, help_text='The Market Intel user who initiated the send (outbound only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('session_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hmac_valid', models.BooleanField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected (invalid signature/schema)'), ('DUPLICATE', 'Duplicate (already processed)')], default='PENDING', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('payload_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='whatsapp.whatsappmessage')),
            ],
            options={
                'verbose_name': 'WhatsApp Event',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_digits', models.CharField(db_index=True, help_text='Digits-only phone number (e.g., 919876543210).', max_length=20, unique=True)),
                ('reason', models.CharField(choices=[('RECIPIENT_REQUEST', 'Recipient requested'), ('ADMIN_ACTION', 'Admin action'), ('INCOMING_KEYWORD', 'Incoming STOP keyword')], max_length=30)),
                ('trigger_message', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_opt_outs', to='prospects.prospectcontact')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_opt_outs_registered', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_opt_outs_reversed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Opt-Out',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSafetyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SAFETY_STOP_TRIGGERED', 'Safety Stop Triggered'), ('SAFETY_STOP_RESET', 'Safety Stop Reset'), ('OUTBOUND_DISABLED', 'Outbound Disabled'), ('OUTBOUND_ENABLED', 'Outbound Enabled'), ('RATE_LIMIT_BLOCKED', 'Rate Limit Block'), ('COOLDOWN_BLOCKED', 'Cooldown Block'), ('OPT_OUT_BLOCKED', 'Opt-Out Block'), ('DUPLICATE_BLOCKED', 'Duplicate Send Block'), ('SESSION_FAILURE', 'Session Failure'), ('CONSECUTIVE_FAILURES', 'Consecutive Failures'), ('ADMIN_EMERGENCY_STOP', 'Admin Emergency Stop')], max_length=30)),
                ('details', models.TextField(blank=True, help_text='Human-readable description of what triggered this event.', null=True)),
                ('consecutive_failures_at_event', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_safety_events', to='prospects.prospectcontact')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='The user whose action triggered this event (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_safety_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Safety Event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('SESSION_STARTED', 'Session Started'), ('SESSION_STOPPED', 'Session Stopped'), ('QR_REQUESTED', 'QR Requested'), ('QR_SCANNED', 'QR Scanned'), ('SESSION_CONNECTED', 'Session Connected'), ('SESSION_DISCONNECTED', 'Session Disconnected'), ('MESSAGE_SENT', 'Message Sent'), ('MESSAGE_RECEIVED', 'Message Received'), ('MESSAGE_FAILED', 'Message Failed'), ('SEND_BLOCKED', 'Send Blocked'), ('OPT_OUT_REGISTERED', 'Opt-Out Registered'), ('OPT_OUT_REVERSED', 'Opt-Out Reversed'), ('SAFETY_STOP', 'Safety Stop'), ('ADMIN_RESUMED', 'Admin Resumed'), ('CONFIG_CHANGED', 'Config Changed')], db_index=True, max_length=30)),
                ('performed_by_role', models.CharField(blank=True, max_length=20, null=True)),
                ('prospect_id', models.UUIDField(blank=True, null=True)),
                ('prospect_name', models.CharField(blank=True, max_length=255, null=True)),
                ('prospect_contact_id', models.UUIDField(blank=True, null=True)),
                ('prospect_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('session_name', models.CharField(blank=True, max_length=100, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message_id', models.UUIDField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('result_code', models.CharField(blank=True, max_length=50, null=True)),
                ('result_detail', models.TextField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Audit Log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='whatsapp_wh_action_fabd03_idx'), models.Index(fields=['performed_by', 'created_at'], name='whatsapp_wh_perform_724880_idx'), models.Index(fields=['prospect_contact_id'], name='whatsapp_wh_prospec_280cfb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['idempotency_key'], name='whatsapp_wh_idempot_9c71f4_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['waha_message_id'], name='whatsapp_wh_waha_me_c83aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['conversation', 'direction', 'created_at'], name='whatsapp_wh_convers_0c03a0_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappevent',
            index=models.Index(fields=['event_type', 'received_at'], name='whatsapp_wh_event_t_dedca5_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappevent',
            index=models.Index(fields=['payload_hash'], name='whatsapp_wh_payload_42ca6f_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappevent',
            index=models.Index(fields=['processing_status'], name='whatsapp_wh_process_f4f331_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappoptout',
            index=models.Index(fields=['phone_digits', 'is_active'], name='whatsapp_wh_phone_d_55f01d_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['chat_id'], name='whatsapp_wh_chat_id_6edeb7_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['prospect_contact'], name='whatsapp_wh_prospec_f06dde_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['is_matched'], name='whatsapp_wh_is_matc_4ff89a_idx'),
        ),
    ]
