# Generated by Django 6.1.1 on 2026-09-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconversation',
            name='whatsapp_name',
            field=models.CharField(blank=True, help_text='Name provided by WhatsApp profile (pushName or notifyName)', max_length=255, null=True),
        ),
    ]
