# Generated by Django 6.1.1 on 2026-09-26 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_whatsappmessage_full_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
