# Generated by Django 6.1.1 on 2026-09-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_alter_whatsappmessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='has_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='whatsapp_media/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
