# Generated by Django 6.1.1 on 2026-09-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_whatsappmessage_has_media_whatsappmessage_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='media_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
