# Generated by Django 6.1.1 on 2026-10-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_whatsapp_session_owner_and_conversation_scoped_uniqueness'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='whatsappconversation',
            new_name='whatsapp_wh_session_8fe92a_idx',
            old_name='whatsapp_co_session_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappmessage',
            new_name='whatsapp_wh_convers_316ee4_idx',
            old_name='whatsapp_ms_conv_deleted_created_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappsession',
            new_name='whatsapp_wh_owner_i_86a0b0_idx',
            old_name='whatsapp_se_owner_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappsession',
            new_name='whatsapp_wh_session_b843b5_idx',
            old_name='whatsapp_se_session_name_idx',
        ),
    ]
