# Generated by Django 6.1.1 on 2026-09-18 06:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('country_head_office', models.CharField(max_length=255)),
                ('complete_address', models.TextField()),
                ('official_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('official_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('official_website_url', models.URLField(blank=True, null=True)),
                ('linkedin_company_page', models.URLField(blank=True, null=True)),
                ('primary_industries', models.CharField(max_length=255)),
                ('company_structure', models.CharField(choices=[('Parent', 'Parent Organization'), ('Branch', 'Branch Office'), ('Subsidiary', 'Subsidiary Company')], max_length=50)),
                ('operational_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Permanently Closed', 'Permanently Closed'), ('Acquired', 'Acquired'), ('Merged', 'Merged')], max_length=50)),
                ('primary_offering_type', models.CharField(choices=[('Products', 'Products'), ('Services', 'Services'), ('Solutions', 'Solutions'), ('Multiple', 'Multiple')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_companies', models.ManyToManyField(blank=True, related_name='child_companies', to='prospects.prospect')),
                ('status_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquired_or_merged_from', to='prospects.prospect')),
            ],
        ),
        migrations.CreateModel(
            name='ProspectContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_contacts', to='prospects.prospect')),
            ],
        ),
        migrations.CreateModel(
            name='ProspectOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offering_type', models.CharField(choices=[('Product', 'Product'), ('Service', 'Service'), ('Solution', 'Solution')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='prospects.prospect')),
            ],
        ),
    ]
