# Generated by Django 6.1.1 on 2026-09-18 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('Unverified', 'Unverified'), ('In Progress', 'In Progress'), ('Verified', 'Verified')], default='Unverified', max_length=50)),
                ('qualification_status', models.CharField(choices=[('Unqualified', 'Unqualified'), ('Hot Lead', 'Hot Lead'), ('Qualified', 'Qualified'), ('Nurture', 'Nurture'), ('Disqualified', 'Disqualified')], default='Unqualified', max_length=50)),
                ('pre_task_status', models.CharField(choices=[('NONE', 'None'), ('ISSUE_SENT_TO_PRE', 'Issue Sent to PRE'), ('PRE_UPDATED', 'PRE Updated Data')], default='NONE', max_length=50)),
                ('qualification_score', models.IntegerField(default=0)),
                ('lq_notes', models.TextField(blank=True, null=True)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('budget', models.BooleanField(default=False)),
                ('authority', models.BooleanField(default=False)),
                ('need', models.BooleanField(default=False)),
                ('timeline', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_qualification', to='prospects.prospect')),
                ('qualified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifications_performed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
