# Generated by Django 6.1.1 on 2026-09-18 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_leadqualification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadqualification',
            name='issue_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadqualification',
            name='issue_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadqualification',
            name='issue_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadqualification',
            name='issue_reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
