# Generated by Django 6.1.1 on 2026-09-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_leadqualification_issue_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadqualification',
            name='verification_checklist',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
