# Generated by Django 6.1.1 on 2026-09-18 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0004_leadqualification_verification_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notified_30m', models.BooleanField(default=False)),
                ('notified_15m', models.BooleanField(default=False)),
                ('notified_5m', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='prospects.prospect')),
            ],
        ),
    ]
