# Generated by Django 6.1.1 on 2026-09-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0006_leadqualification_email_status_outreachlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadqualification',
            name='qualification_status',
            field=models.CharField(choices=[('Unqualified', 'Unqualified'), ('Hot Lead', 'Hot Lead'), ('Qualified', 'Qualified'), ('Nurture', 'Nurture'), ('Disqualified', 'Disqualified'), ('Budget Frozen', 'Budget Frozen'), ('Prospect Selected', 'Prospect Selected')], default='Unqualified', max_length=50),
        ),
    ]
