# Generated by Django 6.1.1 on 2026-09-19 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermailaccount'),
        ('prospects', '0007_alter_leadqualification_qualification_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('ivr_extension', models.CharField(blank=True, max_length=50, null=True)),
                ('call_status', models.CharField(max_length=100)),
                ('communication_outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('call_started_at', models.DateTimeField(blank=True, null=True)),
                ('call_ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_activities', to='prospects.prospect')),
                ('prospect_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_activities', to='prospects.prospectcontact')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=255)),
                ('from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=512)),
                ('body', models.TextField()),
                ('signature', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT SENT', 'Not Sent'), ('SENT', 'Sent'), ('WAITING FOR RESPONSE', 'Waiting for Response'), ('RECEIVED RESPONSE', 'Received Response'), ('FAILED', 'Failed')], default='NOT SENT', max_length=50)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=255, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_emails', to='prospects.prospect')),
                ('sender_mail_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.usermailaccount')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outreach_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='prospects.outreachemail')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('EMAIL_SENT', 'Email Sent'), ('EMAIL_RECEIVED', 'Email Received'), ('CALL', 'Call')], max_length=50)),
                ('direction', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('INBOUND', 'Inbound')], default='OUTBOUND', max_length=20)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=512, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospects.callactivity')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_timeline', to='prospects.prospect')),
                ('prospect_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_timeline', to='prospects.prospectcontact')),
                ('outreach_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospects.outreachemail')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachEmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('recipient_type', models.CharField(choices=[('TO', 'TO'), ('CC', 'CC'), ('BCC', 'BCC')], max_length=10)),
                ('outreach_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='prospects.outreachemail')),
                ('prospect_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prospects.prospectcontact')),
            ],
        ),
    ]
