# Generated by Django 6.1.1 on 2026-09-19 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0009_auto_20260919_0757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutreachLog',
        ),
    ]
