# Generated by Django 6.1.1 on 2026-09-19 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mailaccount_remove_usermailaccount_user_and_more'),
        ('prospects', '0010_delete_outreachlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachemail',
            name='sender_mail_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.mailaccount'),
        ),
    ]
