# Generated by Django 6.1.1 on 2026-09-19 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0011_alter_outreachemail_sender_mail_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callactivity',
            name='prospect_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_activities', to='prospects.prospectcontact'),
        ),
    ]
