# Generated by Django 6.1.1 on 2026-09-19 07:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0012_alter_callactivity_prospect_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=254)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('UNKNOWN', 'Unknown')], default='UNVERIFIED', max_length=50)),
                ('verification_method', models.CharField(choices=[('SYNTAX', 'Syntax'), ('DNS', 'DNS'), ('MX', 'MX'), ('SMTP', 'SMTP'), ('COMBINED', 'Combined'), ('MANUAL_CONFIRMATION', 'Manual Confirmation')], default='COMBINED', max_length=50)),
                ('syntax_valid', models.BooleanField(default=False)),
                ('domain_valid', models.BooleanField(default=False)),
                ('mx_found', models.BooleanField(default=False)),
                ('smtp_checked', models.BooleanField(default=False)),
                ('smtp_valid', models.BooleanField(default=False)),
                ('is_disposable', models.BooleanField(default=False)),
                ('is_role_account', models.BooleanField(default=False)),
                ('is_catch_all', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by_lq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_confirmed', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to='prospects.prospect')),
                ('prospect_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to='prospects.prospectcontact')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('prospect', 'prospect_contact', 'email_address'), name='unique_prospect_contact_email_verification')],
            },
        ),
    ]
