# Generated by Django 6.1.1 on 2026-09-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0015_alter_callactivity_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callactivity',
            name='company',
        ),
        migrations.RemoveField(
            model_name='callbackreminder',
            name='company',
        ),
        migrations.RemoveField(
            model_name='communicationactivity',
            name='company',
        ),
        migrations.RemoveField(
            model_name='emailattachment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='company',
        ),
        migrations.RemoveField(
            model_name='leadqualification',
            name='company',
        ),
        migrations.RemoveField(
            model_name='outreachemail',
            name='company',
        ),
        migrations.RemoveField(
            model_name='outreachemailrecipient',
            name='company',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='company',
        ),
        migrations.RemoveField(
            model_name='prospectcontact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='prospectoffering',
            name='company',
        ),
    ]
