# Generated by Django 6.1.1 on 2026-09-21 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0016_remove_callactivity_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachemail',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='tracking_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leadqualification',
            name='qualification_status',
            field=models.CharField(choices=[('Unqualified', 'Unqualified'), ('Hot Lead', 'Hot Lead'), ('Qualified', 'Qualified'), ('Nurture', 'Nurture'), ('Disqualified', 'Disqualified'), ('Budget Frozen', 'Budget Frozen'), ('Lead Qualified', 'Lead Qualified')], default='Unqualified', max_length=50),
        ),
    ]
