# Generated by Django 6.1.1 on 2026-09-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0017_outreachemail_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadqualification',
            name='attended_meeting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leadqualification',
            name='qualification_status',
            field=models.CharField(choices=[('Unqualified', 'Unqualified'), ('Hot Lead', 'Hot Lead'), ('Qualified', 'Qualified'), ('Nurture', 'Nurture'), ('Disqualified', 'Disqualified'), ('Lead Freeze', 'Lead Freeze'), ('Lead Qualified', 'Lead Qualified')], default='Unqualified', max_length=50),
        ),
    ]
