# Generated by Django 6.1.1 on 2026-09-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0018_leadqualification_attended_meeting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField()),
                ('meeting_link', models.CharField(blank=True, max_length=512, null=True)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notified_1h', models.BooleanField(default=False)),
                ('notified_30m', models.BooleanField(default=False)),
                ('notified_15m', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='prospects.prospect')),
            ],
        ),
    ]
