# Generated by Django 6.1.1 on 2026-09-24 03:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0020_add_lq_audit_timestamp_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outreachemail',
            name='body',
        ),
        migrations.RemoveField(
            model_name='outreachemail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='outreachemail',
            name='in_reply_to',
        ),
        migrations.RemoveField(
            model_name='outreachemail',
            name='is_opened',
        ),
        migrations.RemoveField(
            model_name='outreachemail',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='outreachemail',
            name='opened_at',
        ),
        migrations.RemoveField(
            model_name='outreachemail',
            name='references',
        ),
        migrations.RemoveField(
            model_name='outreachemail',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='outreachemail',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='outreachemail',
            name='status',
        ),
        migrations.RemoveField(
            model_name='outreachemail',
            name='thread_id',
        ),
        migrations.RemoveField(
            model_name='outreachemail',
            name='tracking_token',
        ),
        migrations.RemoveField(
            model_name='outreachemail',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='AuditReverificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted_fields', models.JSONField(default=list)),
                ('manager_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('manager_notified', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('signature', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT SENT', 'Not Sent'), ('SENT', 'Sent'), ('WAITING FOR RESPONSE', 'Waiting for Response'), ('RECEIVED RESPONSE', 'Received Response'), ('FAILED', 'Failed')], default='NOT SENT', max_length=50)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=255, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('tracking_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('is_opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverifications_sent', to=settings.AUTH_USER_MODEL)),
                ('pre_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverifications_received', to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverification_requests', to='prospects.prospect')),
            ],
        ),
    ]
