# Generated by Django 6.1.1 on 2026-09-24 03:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0021_remove_outreachemail_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditreverificationrequest',
            name='body',
        ),
        migrations.RemoveField(
            model_name='auditreverificationrequest',
            name='in_reply_to',
        ),
        migrations.RemoveField(
            model_name='auditreverificationrequest',
            name='is_opened',
        ),
        migrations.RemoveField(
            model_name='auditreverificationrequest',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='auditreverificationrequest',
            name='opened_at',
        ),
        migrations.RemoveField(
            model_name='auditreverificationrequest',
            name='references',
        ),
        migrations.RemoveField(
            model_name='auditreverificationrequest',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='auditreverificationrequest',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='auditreverificationrequest',
            name='thread_id',
        ),
        migrations.RemoveField(
            model_name='auditreverificationrequest',
            name='tracking_token',
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='in_reply_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='status',
            field=models.CharField(choices=[('NOT SENT', 'Not Sent'), ('SENT', 'Sent'), ('WAITING FOR RESPONSE', 'Waiting for Response'), ('RECEIVED RESPONSE', 'Received Response'), ('FAILED', 'Failed')], default='NOT SENT', max_length=50),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='tracking_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auditreverificationrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Corrected', 'Corrected')], default='Pending', max_length=50),
        ),
    ]
