# Generated by Django 6.1.1 on 2026-09-24 03:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0022_remove_auditreverificationrequest_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreachemail',
            name='tracking_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
