# Generated by Django 6.1.1 on 2026-09-24 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0023_alter_outreachemail_tracking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackreminder',
            name='prospect_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='prospects.prospectcontact'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='prospect_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='prospects.prospectcontact'),
        ),
    ]
