# Generated by Django 6.1.1 on 2026-09-28 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0024_callbackreminder_prospect_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadqualification',
            name='assigned_lq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prospects', to=settings.AUTH_USER_MODEL),
        ),
    ]
