# Generated by Django 6.1.1 on 2026-10-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0026_prospect_ownership_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='merger_role',
            field=models.CharField(blank=True, choices=[('Target Company', 'Target Company'), ('Entering Company', 'Entering Company')], max_length=50, null=True),
        ),
    ]
