# Generated by Django 6.1.1 on 2026-10-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0027_prospect_merger_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='merger_role',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='status_target',
        ),
    ]
