# Generated by Django 6.1.1 on 2026-10-06 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0028_remove_prospect_merger_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectShareholding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holder_type', models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual')], max_length=20)),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_shareholdings', to='prospects.prospect')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareholdings', to='prospects.prospectcontact')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholdings', to='prospects.prospect')),
            ],
        ),
    ]
