# Generated by Django 6.1.1 on 2026-10-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0029_prospectshareholding'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='dissolved_companies',
            field=models.ManyToManyField(blank=True, related_name='dissolved_into_prospects', to='prospects.prospect'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='merging_companies',
            field=models.ManyToManyField(blank=True, related_name='merged_into_prospects', to='prospects.prospect'),
        ),
    ]
