# Generated by Django 6.1.1 on 2026-10-06 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0030_prospect_dissolved_companies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('is_state_government', models.BooleanField(default=False)),
                ('official_website', models.URLField(blank=True, null=True)),
                ('official_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('complete_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('central_government', models.ForeignKey(blank=True, limit_choices_to={'is_state_government': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_entities', to='prospects.governmententity')),
            ],
        ),
    ]
