# Generated by Django 6.1.1 on 2026-10-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0031_governmententity'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmententity',
            name='state_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
