# Generated by Django 6.1.1 on 2026-10-06 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0032_governmententity_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectshareholding',
            name='government_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareholdings', to='prospects.governmententity'),
        ),
        migrations.AddField(
            model_name='prospectshareholding',
            name='other_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prospectshareholding',
            name='holder_type',
            field=models.CharField(choices=[('Company', 'Company'), ('Individual', 'Individual'), ('Government', 'Country or State'), ('Other', 'Others')], max_length=20),
        ),
    ]
