# Generated by Django 6.1.1 on 2026-10-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0033_prospectshareholding_government_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectcontact',
            name='prefix',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
