# Generated by Django 6.1.1 on 2026-10-06 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0034_prospectcontact_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='acquired_shares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='acquiring_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquired_companies', to='prospects.prospect'),
        ),
    ]
