# Generated by Django 6.1.1 on 2026-10-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0036_prospectimporthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadqualification',
            name='completed_tasks_log',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
