# Generated by Django 6.1.1 on 2026-10-07 12:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0037_leadqualification_completed_tasks_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='acquired_shares',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='acquiring_company',
        ),
        migrations.CreateModel(
            name='ProspectAcquisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acquired_shares', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acquired_prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_records', to='prospects.prospect')),
                ('acquiring_prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquired_records', to='prospects.prospect')),
            ],
            options={
                'unique_together': {('acquired_prospect', 'acquiring_prospect')},
            },
        ),
        migrations.AddField(
            model_name='prospect',
            name='acquiring_companies',
            field=models.ManyToManyField(blank=True, related_name='acquired_companies_rev', through='prospects.ProspectAcquisition', to='prospects.prospect'),
        ),
    ]
