# Generated by Django 6.1.1 on 2026-09-18 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=255)),
                ('host_country', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketEventParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='market_events.marketevent')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_event_participations', to='prospects.prospect')),
            ],
            options={
                'indexes': [models.Index(fields=['market_event'], name='market_even_market__807ab7_idx'), models.Index(fields=['prospect'], name='market_even_prospec_85e36e_idx')],
                'constraints': [models.UniqueConstraint(fields=('market_event', 'prospect'), name='unique_market_event_prospect')],
            },
        ),
    ]
