# Generated by Django 6.1.1 on 2026-09-18 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketevent',
            name='event_date',
        ),
        migrations.AddField(
            model_name='marketevent',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='marketevent',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
