# Generated by Django 6.1.1 on 2026-09-19 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('market_events', '0002_remove_marketevent_event_date_marketevent_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketevent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
        migrations.AddField(
            model_name='marketeventparticipation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
    ]
