# Generated by Django 6.1.1 on 2026-09-19 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('market_events', '0003_marketevent_company_marketeventparticipation_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
        migrations.AlterField(
            model_name='marketeventparticipation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company'),
        ),
    ]
