# Generated by Django 6.1.1 on 2026-09-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_events', '0004_alter_marketevent_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketevent',
            name='company',
        ),
        migrations.RemoveField(
            model_name='marketeventparticipation',
            name='company',
        ),
    ]
